name: Deploy Spring Boot App to Ubuntu

on:
  push:
    branches:
      - main  # Adjust this to match your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'


      - name: Build Spring Boot Application
        run: mvn clean package  # Adjust for your build tool (e.g., gradle build)

      - name: Create SSH directory
        run: mkdir -p $HOME/.ssh

      - name: Add Ubuntu instance to known hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> $HOME/.ssh/known_hosts

      - name: Transfer JAR to Ubuntu instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "target/todo-1.0.0-SNAPSHOT.jar"  # Adjust the source path if needed
          target: "/home/todo-1.0.0-SNAPSHOT.jar"  # Adjust the target path

      - name: SSH into the Ubuntu instance and start the application (alternative approach)
        run: |
          sshpass -p "${{ secrets.PASSWORD }}" ssh -o StrictHostKeyChecking=no "${{ secrets.USERNAME }}"@${{ secrets.HOST }} "java -jar /path/to/your/application.jar"
        env:
          PASSWORD: ${{ secrets.PASSWORD }}

      # Adjust the path
