name: Deploy Spring Boot App to Ubuntu

on:
  push:
    branches:
      - main  # Adjust this to match your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8

      - name: Build Spring Boot Application
        run: mvn clean package  # Adjust for your build tool (e.g., gradle build)

      - name: Transfer JAR to Ubuntu instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "target/your-application.jar"  # Adjust the source path if needed
          target: "/path/to/destination/your-application.jar"  # Adjust the target path

      - name: SSH into the Ubuntu instance and start the application
        run: ssh ${{ secrets.USERNAME }}@${{ secrets.HOST }} "java -jar /path/to/destination/your-application.jar"  # Adjust the path
